[context.production.environment]
  REACT_APP_ACCESS_ID="AKIA226NQ27M54CMVTLD"
  REACT_APP_ACCESS_KEY="nqgGFIGVwkkH5XaLs5QQA0NjPPGxWrGSsIKlk0k2"
  REACT_APP_BUCKET_NAME="wishly"
  REACT_APP_DIR_NAME="userPic"
  REACT_APP_REGION="eu-central-1"
