### GET ALL USERS
GET http://localhost:5000/api/users
Accept: application/json

### REGISTRATION
POST http://localhost:5000/api/registration
Content-Type: application/json

{
  "email": "harlamov@gmail.com",
  "isActivated": true
}

### REGISTRATION IN EXTENTION
POST http://localhost:5000/api/login/extension
Content-Type: application/json

{
  "_id": "615d4e734279fe2993724474"
}

### CREATE NEW WISHLIST
POST http://localhost:5000/api/addWishlist
Content-Type: application/json

{
  "userId": "6176a2e5efa3d69a3e64a918",
  "name": "second"
}

### ADD NEW URL
POST http://localhost:5000/api/addUrl
Content-Type: application/json

{
  "_id": "6176ab9f0df8bbae121eac2e",
  "url": "https://www.adidas.com/3",
  "nameURL": "nike",
  "image": "imageURL",
  "price": "999"
}

### GET WISHLIST
GET http://localhost:5000/api/wishlist/6176ab9f0df8bbae121eac2e
Content-Type: application/json

### GET WISHLISTS
GET http://localhost:5000/api/user/6176a2e5efa3d69a3e64a918
Content-Type: application/json

### GET CATEGORIES
GET http://localhost:5000/api/categories/6176a2e5efa3d69a3e64a918
Content-Type: application/json
